<?php
    include('./config.php');

    // query_three
    $query_three = "SELECT products.name AS product_name, categories.name AS category_name, products.description, order_items.quantity, order_items.unit_price, SUM(order_items.quantity * order_items.unit_price) AS TotalRevenue FROM products JOIN categories ON products.category_id = categories.category_id JOIN order_items ON products.product_id = order_items.product_id GROUP BY categories.name ORDER BY TotalRevenue DESC";
    $result_three = $mysqli->query($query_three);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ostad - Database Project</title>
    <!-- bootstrap css link  -->
    <link rel="stylesheet" href="./assets/css/bootstrap.min.css">
    <!-- custom css link  -->
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
    <div class="container">
        <div class="row my-5">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <!-- navbar -->
                <?php include('./navbar.php'); ?>
                <!-- navbar -->
                <div class="card p-3 shadow">
                    <p class="">
                        <span class="fw-bold">Task-3: </span>
                        Write a SQL query to retrieve the total revenue generated by each product category. Display the category name along with the total revenue in descending order of the revenue.
                    </p>
                    <table class="table">
                        <thead>
                            <tr>
                            <th scope="col">Product Name</th>
                            <th scope="col">Category Name</th>
                            <th scope="col">Description</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Price</th>
                            <th scope="col">Total Revenue</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php while($row_three = $result_three->fetch_assoc()){ ?>
                            <tr>
                                <th scope="row"><?php echo $row_three['product_name']; ?></th>
                                <td><?php echo $row_three['category_name']; ?></td>
                                <td><?php echo $row_three['description']; ?></td>
                                <td><?php echo $row_three['quantity']; ?></td>
                                <td><?php echo $row_three['unit_price']; ?></td>
                                <td><?php echo $row_three['TotalRevenue']; ?></td>
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>

    <script src="./assets/js/bootstrap.bundle.min.js"></script>
</body>
</html>